[package]
name = "mapdiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.92"}
toml = "0.7.1"
octocrab = "0.18.1"
flume = "0.10.14"
dmm-tools = { git = "https://github.com/SpaceManiac/SpacemanDMM/", features = ["png"] }
dreammaker = { git = "https://github.com/SpaceManiac/SpacemanDMM/" }
ahash = "0.8.3"
path-absolutize = "3.0.14"
jsonwebtoken = "8.2.0"
lazy_static = "1.4.0"
eyre = "0.6.8"
stable-eyre = "0.2"
rayon = "1.6.1"
derive_builder = "0.12.0"
once_cell = "1.17.0"
image = "0.24.5"
glob = "0.3.1"
diffbot_lib = { path = "../diffbot_lib" }
yaque = "0.6.4"
walkdir = "2.3.2"
delay_timer = "0.11.3"
hex = { version = "0.4.3", features = ["serde"] }
gix = { version = "0.35.0", features = ["blocking-network-client", "blocking-http-transport-reqwest", "blocking-http-transport-reqwest-rust-tls"] }

actix-web = "4.3.0"
actix-files = "0.6.2"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.0"

