[package]
name = "icondiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
octocrab = "0.18.1"
dmm-tools = { git = "https://github.com/SpaceManiac/SpacemanDMM/", features = ["png", "gif"] }
dreammaker = { git = "https://github.com/SpaceManiac/SpacemanDMM/" }
once_cell = "1.17.0"
jsonwebtoken = "8.2.0"
lazy_static = "1.4.0"
reqwest = "0.11.13"
diffbot_lib = { path = "../diffbot_lib" }
eyre = "0.6.8"
stable-eyre = "0.2"
ndarray = "0.15.6"
rayon = "1.6.1"
toml = "0.5.10"
ahash = "0.8.2"
hashbrown = { version = "0.13.2", features = ["rayon"]}
yaque = "0.6.4"
hex = { version = "0.4.3", features = ["serde"] }

actix-web = "4.2.1"
actix-files = "0.6.2"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.0"

[dependencies.tracing]
version = "0.1.37"
features = ["attributes"]
