[package]
name = "icondiffbot2"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
octocrab = "0.25.1"
dmm-tools = { git = "https://github.com/jupyterkat/SpacemanDMM/", branch = "legacy", features = ["gif", "png"] }
dreammaker = { git = "https://github.com/jupyterkat/SpacemanDMM/", branch = "legacy" }
once_cell = "1.18.0"
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
reqwest = "0.11.18"
diffbot_lib = { path = "../diffbot_lib" }
eyre = "0.6.8"
simple-eyre = "0.3.1"
ndarray = "0.15.6"
rayon = "1.7.0"
toml = "0.7.6"
ahash = "0.8.3"
hashbrown = { version = "0.14.0", features = ["rayon"]}
yaque = { git = "https://github.com/jupyterkat/yaque" }
hex = { version = "0.4.3", features = ["serde"] }
itertools = "0.11.0"

actix-web = "4.3.1"
actix-files = "0.6.2"

mysql_async = "0.32.2"
time = "0.3.23"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.0"

[dependencies.tracing]
version = "0.1.37"
features = ["attributes"]
