# Blacklisted repos, and message to show on blacklisted repo's jobs (Optional)
blacklist = [
    1337,
]
blacklist_contact = "Good luck!"

# Logging level (Optional, defaults to info), Valid values are "info", "warn", "trace", "error", "debug"
logging = "info"

# Webhook secret (Optional, payload verification w/ SHA is disabled if not set)
# secret = "abcdef"

# Github credentials (Required)
[github]
app_id = 123456
private_key_path = "diffbot.pem"

# Server details (Required)
[web]
address = "0.0.0.0"
port = 1234
# Server host for images (Required)
file_hosting_url = "http://example.com:1234/images"

# Actixweb forms and string limits (Optional)
[web.limits]
forms = 131072
string = 131072

