[package]
name = "diffbot_lib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
octocrab = "0.18.1"
eyre = "0.6.8"
derive_builder = "0.12.0"
chrono = "0.4.23"
reqwest = "0.11.14"
yaque = "0.6.4"
futures-lite = "1.12.0"
log = "0.4.17"
simplelog = "0.12.0"
sha2 = "0.10.6"
hmac = "0.12.1"
hex = "0.4.3"

actix-web = "4.3.0"

async-fs = "1.6.0"
async-mutex = "1.4.0"
