[package]
name = "diffbot_lib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
octocrab = "0.23.0"
eyre = "0.6.8"
derive_builder = "0.12.0"
chrono = "0.4.24"
reqwest = "0.11.17"
yaque = { git = "https://github.com/jupyterkat/yaque" }
futures-lite = "1.13.0"
log = "0.4.17"
simplelog = "0.12.1"
sha2 = "0.10.6"
hmac = "0.12.1"
hex = "0.4.3"

actix-web = "4.3.1"

async-fs = "1.6.0"
async-mutex = "1.4.0"
