[package]
name = "diffbot_lib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
octocrab = "0.28.0"
eyre = "0.6.8"
derive_builder = "0.12.0"
chrono = "0.4.26"
reqwest = "0.11.18"
yaque = { git = "https://github.com/jupyterkat/yaque" }
futures-lite = "1.13.0"
log = "0.4.19"
simple_logger = "4.2.0"
sha2 = "0.10.7"
hmac = "0.12.1"
hex = "0.4.3"

actix-web = "4.3.1"

async-fs = "1.6.0"
async-mutex = "1.4.0"
